import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/content/components/header'
import Footer from '@/content/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <div className="content-wrapper">
            <Header />
            {/* /header */}
            <section>
              <div className="hero-slider-wrapper bg-dark">
                <div className="hero-slider owl-carousel dots-over" data-nav="true" data-dots="true" data-autoplay="true">
                  <div className="owl-slide d-flex align-items-center bg-overlay bg-overlay-400 slide-image-3" style={{ backgroundImage: 'url(assets/img/banners/banner-3.webp)' }}>
                    <div className="container">
                      <div className="row">
                        <div style={{ color: '#fff!important' }} className="col-md-10 offset-md-1 col-lg-7 offset-lg-0 col-xl-6 col-xxl-5 text-center text-lg-start">
                          <div className="lead fs-23 lh-sm animated-caption" data-anim="animate__slideInRight" data-anim-delay={1000}>Real Estate</div>
                          <h2 style={{ color: '#fff!important' }} className="display-1 fs-56 mb-4 animated-caption" data-anim="animate__slideInDown" data-anim-delay={500}>Discover The Best Assets on Earth</h2>
                          <div className="animated-caption" data-anim="animate__slideInUp" data-anim-delay={1500}><a href="https://superlabs.co/circle-realty" target="_blank" style={{ color: '#fff' }} className="more hover fs-18">LEARN MORE</a>
                          </div>
                        </div>
                        {/*/column */}
                      </div>
                      {/*/.row */}
                    </div>
                    {/*/.container */}
                  </div>
                  {/*/.owl-slide */}
                  <div className="owl-slide d-flex align-items-center bg-overlay bg-overlay-400 slide-image-4" style={{ backgroundImage: 'url(assets/img/banners/banner-4.jpg)' }}>
                    <div className="container">
                      <div className="row">
                        <div style={{ color: '#fff!important' }} className="col-md-10 offset-md-1 col-lg-7 offset-lg-0 col-xl-6 col-xxl-5 text-center text-lg-start">
                          <div className="lead fs-23 lh-sm animated-caption" data-anim="animate__slideInRight" data-anim-delay={1000}>Engineering</div>
                          <h2 style={{ color: '#fff!important' }} className="display-1 fs-56 mb-4 animated-caption" data-anim="animate__slideInDown" data-anim-delay={500}>Prototyping for the most complex components</h2>
                          <div className="animated-caption" data-anim="animate__slideInUp" data-anim-delay={1500}><a href="https://superlabs.co/engineering-services" target="_blank" style={{ color: '#fff' }} className="more hover fs-18">LEARN MORE</a>
                          </div>
                        </div>
                        {/*/column */}
                      </div>
                      {/*/.row */}
                    </div>
                    {/*/.container */}
                  </div>
                  {/*/.owl-slide */}
                  <div className="owl-slide d-flex align-items-center bg-overlay bg-overlay-400 slide-image" style={{ backgroundImage: 'url(assets/img/banners/banner-1.webp)' }}>
                    <div className="container">
                      <div className="row">
                        <div style={{ color: '#fff!important' }} className="col-md-10 offset-md-1 col-lg-7 offset-lg-0 col-xl-6 col-xxl-5 text-center text-lg-start">
                          <div className="lead fs-23 lh-sm animated-caption" data-anim="animate__slideInRight" data-anim-delay={1000}>Sustainable Agriculture</div>
                          <h2 style={{ color: '#fff!important' }} className="display-1 fs-56 mb-4 animated-caption" data-anim="animate__slideInDown" data-anim-delay={500}>Then. Now. <br /> Next.</h2>
                          <a href="#" target="_blank" style={{ color: '#fff' }} className="more hover fs-18">LEARN MORE</a>
                        </div>
                        {/*/column */}
                      </div>
                      {/*/.row */}
                    </div>
                    {/*/.container */}
                  </div>
                  {/*/.owl-slide */}
                  <div className="owl-slide d-flex align-items-center bg-overlay bg-overlay-400 slide-image-2" style={{ backgroundImage: 'url(assets/img/banners/banner-2.webp)' }}>
                    <div className="container">
                      <div className="row">
                        <div style={{ color: '#fff!important' }} className="col-md-10 offset-md-1 col-lg-7 offset-lg-0 col-xl-6 col-xxl-5 text-center text-lg-start">
                          <div className="lead fs-23 lh-sm animated-caption" data-anim="animate__slideInRight" data-anim-delay={1000}>Life Saving Medical Devices</div>
                          <h2 style={{ color: '#fff!important' }} className="display-1 fs-56 mb-4 animated-caption" data-anim="animate__slideInDown" data-anim-delay={500}>Building for better access</h2>
                          <div className="animated-caption" data-anim="animate__slideInUp" data-anim-delay={1500}><a href="#" target="_blank" style={{ color: '#fff' }} className="more hover fs-18">LEARN MORE</a>
                          </div>
                        </div>
                        {/*/column */}
                      </div>
                      {/*/.row */}
                    </div>
                    {/*/.container */}
                  </div>
                  {/*/.owl-slide */}
                </div>
                {/*/.hero-slider */}
              </div>
            </section>
            <div><br /><br /><br /><br /><br /><br /></div>
            <section className="wrapper bg-gray">
              <div className="container">
                <div className="card shadow-none my-n15 my-lg-n17">
                  <div className="card-body py-12 py-lg-14 px-lg-11 py-xl-16 px-xl-13">
                    <div className="row text-center">
                      <div className="col-lg-9 col-xl-8 col-xxl-7 mx-auto">
                        <h2 className="fs-15 text-uppercase text-muted mb-3">What We Do?</h2>
                        <h3 className="display-4 mb-9">We champion the bold to achieve the extraordinary.</h3>
                      </div>
                      {/* /column */}
                    </div>
                    {/* /.row */}
                    <div className="row gx-md-8 gx-xl-12 gy-8 mb-14 mb-md-11 text-center">
                      <div className="col-md-4">
                        <div className="icon btn btn-block btn-lg btn-soft-purple disabled mb-5"> <i className="uil uil-processor" /> </div>
                        <h4>Application Development</h4>
                        <div className="mb-3">We build software that empowers organizations to effectively integrate their data, decisions, and operations at scale across platforms.</div>
                        <a href="it-services" className="more hover link-purple">Explore IT Services</a>
                      </div>
                      {/*/column */}
                      <div className="col-md-4">
                        <div className="icon btn btn-block btn-lg btn-soft-green disabled mb-5"> <i className="uil uil-cog" /> </div>
                        <h4>Engineering Development</h4>
                        <div className="mb-3">Bespoke engineering services to develop &amp; build new products or reengineering product iterations for better market fit and product growth.</div>
                        <a href="engineering-services" className="more hover link-green">Explore Engineering Services</a>
                      </div>
                      {/*/column */}
                      <div className="col-md-4">
                        <div className="icon btn btn-block btn-lg btn-soft-orange disabled mb-5"> <i className="uil uil-laptop-cloud" /> </div>
                        <h4>Resource Augmentation</h4>
                        <div className="mb-3">Offsite team management &amp; quick ramp up for rapid growth, instant access to a talent pool of over 60+ mid &amp; senior level engineers.</div>
                        <a href="resource-augmentation" className="more hover link-orange">On board Resources</a>
                      </div>
                      {/*/column */}
                    </div>
                    {/*/.row */}
                    <div className="row gx-md-8 gx-xl-12 gy-10 align-items-center">
                      <div className="col-lg-6">
                        <h2 className="fs-15 text-uppercase text-muted mb-3">SuperLabs Strategy</h2>
                        <h3 className="display-4 mb-5">Understanding business values &amp; challenges.</h3>
                        <div>Bespoke solutions at the core of every business decision to ensure solutions fit real world challenges of the business with ease.</div>
                        <div className="mb-6">We deliver well-suited solutions that ensure business sustainability and high performance, with continous mointering to ensure consistent growth and solutions that stay on track.</div>
                        <a href="strategy.php" className="btn btn-primary rounded-pill mb-0">Explore Strategy</a>
                      </div>
                      {/*/column */}
                      <div className="col-lg-6">
                        <div className="d-flex flex-row">
                          <div>
                            <span className="icon btn btn-block btn-lg btn-soft-purple disabled mt-1 me-5"><span className="number fs-22">01</span></span>
                          </div>
                          <div>
                            <h4 className="mb-1">END-TO-END Business Solution</h4>
                            <div className="mb-0">Integrate end to end user scenarios across all platforms &amp; multiple software products that properly exchange data &amp; interact under the hood.</div>
                          </div>
                        </div>
                        <div className="d-flex flex-row mt-8 ms-lg-10">
                          <div>
                            <span className="icon btn btn-block btn-lg btn-soft-green disabled mt-1 me-5"><span className="number fs-22">02</span></span>
                          </div>
                          <div>
                            <h4 className="mb-1">Customer Success Management</h4>
                            <div className="mb-0">Make sure that your feedback is duly translated to our development team with a customer success manager.</div>
                          </div>
                        </div>
                        <div className="d-flex flex-row mt-8">
                          <div>
                            <span className="icon btn btn-block btn-lg btn-soft-orange disabled mt-1 me-5"><span className="number fs-22">03</span></span>
                          </div>
                          <div>
                            <h4 className="mb-1">Delivery Optimization</h4>
                            <div className="mb-0">Ensure regular and smooth releases and feature updates with enhanced development velocity.</div>
                          </div>
                        </div>
                      </div>
                      {/*/column */}
                    </div>
                    {/*/.row */}
                    <hr className="my-14 my-md-16" />
                    <div className="row gx-lg-8 gx-xl-12 gy-10 gy-lg-0 mb-11 align-items-end">
                      <div className="col-lg-4">
                        <h2 className="fs-15 text-uppercase text-muted mb-3">Impact</h2>
                        <h3 className="display-4 mb-0">Bold steps forward.</h3>
                      </div>
                      {/* /column */}
                      <div className="col-lg-8 mt-lg-2">
                        <div className="row align-items-center counter-wrapper gy-6 text-center">
                          <div className="col-md-4">
                            <h3 className="counter counter-lg">27+</h3>
                            <div>High Impact Projects</div>
                          </div>
                          {/*/column */}
                          <div className="col-md-4">
                            <h3 className="counter counter-lg">10000+</h3>
                            <div>Active Users</div>
                          </div>
                          {/*/column */}
                          <div className="col-md-4">
                            <h3 className="counter counter-lg">162+</h3>
                            <div>Technologies</div>
                          </div>
                          {/*/column */}
                        </div>
                        {/*/.row */}
                      </div>
                      {/* /column */}
                    </div>
                    {/* /.row */}
                    <div className="card bg-gray shadow-lg mb-14 mb-md-17">
                      <div className="row gx-0">
                        <div className="col-lg-6 image-wrapper bg-image bg-cover rounded-top rounded-lg-start" data-image-src="assets/img/our-projects.gif" alt="our-project">
                        </div>
                        {/*/column */}
                        <div className="col-lg-6">
                          <div className="p-10 p-xl-13">
                            <div className="basic-slider owl-carousel gap-small" data-margin={30}>
                              <div className="item">
                                <blockquote className="icon icon-top fs-lg text-center">
                                  <div>“Building an ultra luxury real estate platfrom pan India from the ground up has been a challenge &amp; rewarding journey.”</div>
                                  <div className="blockquote-details justify-content-center text-center">
                                    <div className="info ps-0">
                                      <h5 className="mb-1">Circle Realty</h5>
                                      <div className="mb-0">Real Estate</div>
                                    </div>
                                  </div>
                                </blockquote>
                              </div>
                              {/* /.item */}
                              <div className="item">
                                <blockquote className="icon icon-top fs-lg text-center">
                                  <div>“Cookkart is India's Largest Online Marketplace with over 10000+ products for the professionals.”</div>
                                  <div className="blockquote-details justify-content-center text-center">
                                    <div className="info ps-0">
                                      <h5 className="mb-1">Cookkart</h5>
                                      <div className="mb-0">HORECA</div>
                                    </div>
                                  </div>
                                </blockquote>
                              </div>
                              {/* /.item */}
                              <div className="item">
                                <blockquote className="icon icon-top fs-lg text-center">
                                  <div>“Enable seamless connections based on location &amp; activities for users across the spectrum, making it easy to connect.”</div>
                                  <div className="blockquote-details justify-content-center text-center">
                                    <div className="info ps-0">
                                      <h5 className="mb-1">Kntag</h5>
                                      <div className="mb-0">Software Platforms</div>
                                    </div>
                                  </div>
                                </blockquote>
                              </div>
                              {/* /.item */}
                            </div>
                            {/* /.owl-carousel */}
                          </div>
                          {/*/div */}
                        </div>
                        {/*/column */}
                      </div>
                      {/*/.row */}
                    </div>
                    {/* /.card */}
                    <div className="row text-center">
                      <div className="col-lg-10 col-xl-10 col-xxl-8 mx-auto">
                        <h2 className="fs-15 text-uppercase text-muted mb-3">Impact Studies</h2>
                        <h3 className="display-4 mb-9">See how we’ve helped ambitious clients achieve extraordinary outcomes.</h3>
                      </div>
                      {/* /column */}
                    </div>
                    {/* /.row */}
                    <div className="carousel owl-carousel blog grid-view mb-18" data-margin={30} data-dots="true" data-autoplay="false" data-autoplay-timeout={5000} data-responsive="{&quot;0&quot;:{&quot;items&quot;: &quot;1&quot;}, &quot;768&quot;:{&quot;items&quot;: &quot;2&quot;}, &quot;992&quot;:{&quot;items&quot;: &quot;2&quot;}, &quot;1200&quot;:{&quot;items&quot;: &quot;3&quot;}}">
                      <div className="item">
                        <article>
                          <figure className="overlay overlay1 hover-scale rounded mb-6"><a href="#"> <img src="assets/img/1xdh.jpg" alt="1xdh" /></a>
                            <figcaption>
                              <h5 className="from-top mb-0">Know more</h5>
                            </figcaption>
                          </figure>
                          <div className="post-header">
                            <h2 className="post-title h3 mb-3"><a className="link-dark" href="./blog-post.html">Managed servers, Domains &amp; Professional Emails for Businesses</a></h2>
                          </div>
                          {/* /.post-header */}
                          <div className="post-footer">
                            <ul className="post-meta">
                              <li className="post-comments"><a href="#"><i className="uil uil-file-alt fs-15" />PaaS</a></li>
                            </ul>
                            {/* /.post-meta */}
                          </div>
                          {/* /.post-footer */}
                        </article>
                        {/* /article */}
                      </div>
                      {/* /.item */}
                      <div className="item">
                        <article>
                          <figure className="overlay overlay1 hover-scale rounded mb-6"><a href="./circle-realty.php"> <img src="assets/img/circle-realty.jpg" alt="Circle Realty" /></a>
                            <figcaption>
                              <h5 className="from-top mb-0">Know more</h5>
                            </figcaption>
                          </figure>
                          <div className="post-header">
                            <h2 className="post-title h3 mb-3"><a className="link-dark" href="./circle-realty.php">Ultra Luxury Property Listing With Value Over 1000Cr</a></h2>
                          </div>
                          {/* /.post-header */}
                          <div className="post-footer">
                            <ul className="post-meta">
                              <li className="post-comments"><a href="#"><i className="uil uil-file-alt fs-15" />Real Estate</a></li>
                            </ul>
                            {/* /.post-meta */}
                          </div>
                          {/* /.post-footer */}
                        </article>
                        {/* /article */}
                      </div>
                      {/* /.item */}
                      <div className="item">
                        <article>
                          <figure className="overlay overlay1 hover-scale rounded mb-6"><a href="#"> <img src="assets/img/medical-devices.jpg" alt="1mdm" /></a>
                            <figcaption>
                              <h5 className="from-top mb-0">Know more</h5>
                            </figcaption>
                          </figure>
                          <div className="post-header">
                            <h2 className="post-title h3 mb-3"><a className="link-dark" href="./blog-post.html">Medical Devices Marketplace, Enabling ease of access</a></h2>
                          </div>
                          {/* /.post-header */}
                          <div className="post-footer">
                            <ul className="post-meta">
                              <li className="post-comments"><a href="#"><i className="uil uil-file-alt fs-15" />eCommerce</a></li>
                            </ul>
                            {/* /.post-meta */}
                          </div>
                          {/* /.post-footer */}
                        </article>
                        {/* /article */}
                      </div>
                      {/* /.item */}
                      <div className="item">
                        <article>
                          <figure className="overlay overlay1 hover-scale rounded mb-6"><a href="#"> <img src="assets/img/cookkart.jpg" alt="Cookkart Project" /></a>
                            <figcaption>
                              <h5 className="from-top mb-0">Know more</h5>
                            </figcaption>
                          </figure>
                          <div className="post-header">
                            <h2 className="post-title h3 mb-3"><a className="link-dark" href="./blog-post.html">India's Largest Professional Kitchen Machines Marketplace</a></h2>
                          </div>
                          <div className="post-footer">
                            <ul className="post-meta">
                              <li className="post-comments"><a href="#"><i className="uil uil-file-alt fs-15" />PaaS</a></li>
                            </ul>
                            {/* /.post-meta */}
                          </div>
                          {/* /.post-footer */}
                        </article>
                        {/* /article */}
                      </div>
                      {/* /.item */}
                    </div>
                    {/* /.owl-carousel */}
                    <hr className="my-14 my-md-16" />
                    <div className="row gx-lg-8 gx-xl-12 gy-10 mb-14 mb-md-17 align-items-center">
                      <div className="col-md-8 col-lg-6 order-lg-2">
                        <figure className="rounded"><img src="assets/img/choose-our-team.jpg" srcSet="assets/img/choose-our-team.jpg" alt="Choose Our Team" /></figure>
                      </div>
                      {/*/column */}
                      <div className="col-lg-6">
                        <h2 className="fs-15 text-uppercase text-muted mb-3">Strategy &amp; Consulting</h2>
                        <h3 className="display-4 mb-5">Save your time by choosing our professional team.</h3>
                        <div className="mb-6">Book a free consulting with our professional to understand how we can serve your business better.</div>
                        <div className="row gy-3 gx-xl-8">
                          <div className="col-xl-6">
                            <ul className="icon-list bullet-bg bullet-soft-primary mb-0">
                              <li><span><i className="uil uil-check" /></span><span>Digital Presence Audit.</span></li>
                              <li className="mt-3"><span><i className="uil uil-check" /></span><span>Social Media Network Audit.</span></li>
                            </ul>
                          </div>
                          {/*/column */}
                          <div className="col-xl-6">
                            <ul className="icon-list bullet-bg bullet-soft-primary mb-0">
                              <li><span><i className="uil uil-check" /></span><span>360 Application Audit.</span></li>
                              <li className="mt-3"><span><i className="uil uil-check" /></span><span>Pre launch &amp; Post launch checklist.</span></li>
                            </ul>
                          </div>
                          {/*/column */}
                        </div>
                        {/*/.row */}
                      </div>
                      {/*/column */}
                    </div>
                    {/*/.row */}
                    <div className="row gy-10 gx-8 gx-lg-12 mb-14 mb-md-3 align-items-center">
                      <div className="col-md-8 col-lg-6">
                        <figure className="rounded"><img src="assets/img/careers.jpg" srcSet="assets/img/careers.jpg" alt="careers" /></figure>
                      </div>
                      {/*/column */}
                      <div className="col-lg-6">
                        <h2 className="fs-15 text-uppercase text-muted">Careers</h2>
                        <h3 className="display-4 mb-7">SuperLabs &amp; You.</h3>
                        <div className="accordion accordion-wrapper" id="accordionExample">
                          <div className="card plain accordion-item">
                            <div className="card-header" id="headingOne">
                              <button className="accordion-button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">Full Stack PHP Dev </button>
                            </div>
                            {/*/.card-header */}
                            <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                              <div className="card-body">
                                <div>Knowledge of multiple back-end languages like C#, Java, Python and JavaScript frameworks (e.g. Angular, React, Node.js). <a href="job-php-developer.php" target>Apply now<i className="uil uil-check fs-15" /></a></div>
                              </div>
                              {/*/.card-body */}
                            </div>
                            {/*/.accordion-collapse */}
                          </div>
                          {/*/.accordion-item */}
                          <div className="card plain accordion-item">
                            <div className="card-header" id="headingTwo">
                              <button className="collapsed" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"> Sr .Net Developer </button>
                            </div>
                            {/*/.card-header */}
                            <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                              <div className="card-body">
                                <div>8+ Years experience in.NET languages  like C# and Visual Basic .NET. <a href="job-dotnet-developer.php" target>Apply now<i className="uil uil-check fs-15" /></a></div>
                              </div>
                              {/*/.card-body */}
                            </div>
                            {/*/.accordion-collapse */}
                          </div>
                          {/*/.accordion-item */}
                          <div className="card plain accordion-item">
                            <div className="card-header" id="headingThree">
                              <button className="collapsed" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> HR Manager</button>
                            </div>
                            {/*/.card-header */}
                            <div id="collapseThree" className="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                              <div className="card-body">
                                <div> Experienced &amp; proactive HR manager with at least 5+ years of experience in the IT sector. <a href="job-hr-it-Recruiter.php" target>Apply now<i className="uil uil-check fs-15" /></a></div>
                              </div>
                              {/*/.card-body */}
                            </div>
                            {/*/.accordion-collapse */}
                          </div>
                          {/*/.accordion-item */}
                        </div>
                        {/*/.accordion */}
                      </div>
                      {/*/column */}
                    </div>
                    {/*/.row */}
                    {/* /.wrapper */}
                  </div>
                  {/*/.card-body */}
                </div>
                {/*/.card */}
              </div>
              {/* /.container */}
            </section>
            {/* /section */}
            <br /><br /><br /><br /><br /><br />
          </div>
          {/* /.content-wrapper */}
          <section className="wrapper bg-primary text-center align-items-center">
            <div className="container py-1 py-md-1 align-items-center">
              <div className="container py-1 py-md-6 align-items-center">
                <br /><br />
                <div className="row gx-lg-8 gx-xl-12 gy-10 align-items-center">
                  <div id="border" className="col-lg-6 order-lg-1">
                    <div className="row gx-lg-8 gx-xl-12 gy-6 process-wrapper">
                      <figure>
                        <h3 style={{ color: '#fff' }} className="display-4 mb-5">Where will your career take you?</h3>
                        <br />
                        <a href="careers" style={{ margin: 'auto' }} className="btn btn-outline-white rounded-pill">Come Find Out</a>
                      </figure>
                      {/*/column */}
                    </div>
                  </div>
                  <br /><br />
                  {/*/column */}
                  <div className="col-lg-6">
                    <figure>
                      <h3 style={{ color: '#fff' }} className="display-4 mb-5">What can we help you achieve?</h3>
                      <br />
                      <a href="contact-us" style={{ margin: 'auto' }} className="btn btn-outline-white rounded-pill">Let's Get To Work</a>
                    </figure>
                    {/*/.row */}
                  </div>
                  {/*/column */}
                </div>
              </div>
            </div>
            <br /><br />
          </section>
          <Footer />
          {/* /Footer */}
          <div className="sbuttons">
            <a href="https://wa.me/+919943005109?text=SuperLabs" target="_blank" className="sbutton gplus" tooltip="Whatsapp"><i className="fab fa-whatsapp" /></a>
            <a href="mailto: cr@superlabs.co" target="_blank" className="sbutton pinteres" tooltip="Mail"><i className="fas fa-envelope" /></a>
            <a className="sbutton mainsbutton" tooltip="Lets Talk"><i style={{ color: '#eb252d' }} className="far fa-comment-alt" /></a>
          </div>
          <style dangerouslySetInnerHTML={{ __html: "\n\n@media only screen and (max-width: 992px) {\n#border{\nborder-bottom: 1px solid #fff;\nborder-left: none;\n}\n}\n\n#border{\nborder-left: 1px solid #fff;\n}\n\n.sbuttons {\nbottom: 1%;\nposition: fixed;\nmargin: 1em;\nright: 0;\n}\n.sbutton {\ndisplay: block;\nwidth: 40px;\nheight: 40px;\nborder-radius: 40%;\ntext-align: center;\ncolor: white;\nmargin: 20px auto 0;\ncursor: pointer;\n\nposition: relative;\n}\n.sbutton > i {\nfont-size: 20px;\nline-height: 43px;\n}\n.sbutton:not(:last-child) {\nwidth: 40px;\nheight: 40px;\nmargin: 20px auto 0;\nopacity: 0;\n}\n.sbutton:not(:last-child) > i {\nfont-size: 24px;\nline-height: 38px;\n}\n.sbuttons:hover .sbutton:not(:last-child) {\nopacity: 1;\nwidth: 40px;\nheight: 40px;\nmargin: 15px auto 0;\n}\n\n\n[tooltip]:before {\nfont-family: 'Roboto';\nborder-radius: 10px;\nbackground-color: #585858;\ncolor: #fff;\ncontent: attr(tooltip);\nfont-size: 12px;\nvisibility: hidden;\nopacity: 0;\npadding: 2px 5px;\nmargin-left: 10px;\nposition: absolute;\nright: 100%;\nbottom: 20%;\nwhite-space: nowrap;\nbackground-color: #E5E5E5;\ncolor: black;\n}\n\n[tooltip]:hover:before,\n[tooltip]:hover:after {\nvisibility: visible;\nopacity: 1;\n}\n.sbutton.mainsbutton {\nbackground-image: #eb252d;\nbox-shadow: 0 1px 4px 0 rgb(255 0 9 / 81%);\nmargin-bottom: 22px;\n}\n.sbutton.gplus {\nbackground-image: linear-gradient(to right, #25D366 , #25D366);\n}\n.sbutton.pinteres {\nbackground-image: linear-gradient(to right, #4ECDC4 , #556270);\n}\n.sbutton.twitt {\nbackground-image: linear-gradient(to right, #1DA1F2 , #1DA1F2);\n}\n.sbutton.fb {\nbackground-image: linear-gradient(to right , #C13584  , #FD1D1D , #FFDC80);\n}\n.sbutton.whatsapp {\nbackground-image: linear-gradient(to right, #00B2FF , #006AFF);\n}\n" }} />
        </div>


      </main>
    </>
  )
}
